alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias you='yt-dlp -o "/home/naomi/Videos/youtube/%(title)s - %(uploader)s.%(ext)s"'
alias aud='yt-dlp -f 251 -x -o "/home/naomi/Music/%(title)s - %(uploader)s.%(ext)s"'
alias playlist='yt-dlp -f 251 -x -o "/home/naomi/Music/playlists/%(playlist)s/%(uploader)s - %(title)s.%(ext)s"'
alias pkg='~/mppmg/pkg.sh'
